### ISSUE TITLE
Server chokes after several hours of hosting

### ISSUE THREAD

**Issue by Ipquarx** [Pecon/Dungeon-Generator#1]
After a while (on the order of hours) of hosting, side effects ranging from server-sided lag to complete failure for clients to ghost bricks can happen.

Additional details added by others maybe?

**Comment by Pecon** [comment]
This problem has been mitigated by simply reducing the number of non-brick ghosts that add up during the server run; but is still not 'fixed'.

Lag from clients connecting/disconnecting seems to have been fixed ever since scriptobjects were added to the cleanup group, like they probably should have always been in.

**Comment by ConanODoyle** [comment]
Still exists, specifically when players join/leave the minigame. Should look into the minigame code and see whats going on.

**Comment by Pecon** [comment]
Lag from clients joining/leaving the minigame was fixed (again) by ensuring they're added to the proper cleanup group and not left in missioncleanup.
